eapiVersion: v1
kind: ServiceAccount
metadata:
  name: activator
  namespace: preview
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: activator-role
  namespace: preview
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: activator-rolebinding
  namespace: preview
subjects:
  - kind: ServiceAccount
    name: activator
    namespace: preview
roleRef:
  kind: Role
  name: activator-role
  apiGroup: rbac.authorization.k8s.io 